### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by bapkoala** [neonightmare/homebridge-yamaha#19]
Hi, could you please help with solving this issue?

Rapsberry pi 2, npm 5.8.0, Jeedom (to use the home bridge plugin)

After installed like : `sudo npm install -g homebridge-yamaha`

I have this in the log : 

> [2018-4-15 09:01:33] ====================
> [2018-4-15 09:01:33] ERROR LOADING PLUGIN homebridge-yamaha:
> [2018-4-15 09:01:33] Error: Cannot find module '../build/Release/dns_sd_bindings'
> at Function.Module._resolveFilename (module.js:547:15)
> at Function.Module._load (module.js:474:25)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object.<anonymous> (/usr/lib/node_modules/homebridge-yamaha/node_modules/mdns/lib/dns_sd.js:32:22)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> [2018-4-15 09:01:33] ====================

Thanks

**Comment by naveedyassin** [comment]
sudo apt-get update
sudo apt-get install build-essential libavahi-compat-libdnssd-dev
--------
sudo npm rebuild --unsafe-perm
sudo npm install -g homebridge-yamaha --unsafe-perm
