### ISSUE TITLE
Installed but platform 'YahamhaAVR' not registered by any plugin

### ISSUE THREAD

**Issue by MPV** [neonightmare/homebridge-yamaha#3]
I have installed the plugin:

```
$ npm list -g | grep homebridge

├─┬ homebridge@0.2.11
├─┬ homebridge-http@0.0.3
├─┬ homebridge-ifttt@0.2.0
├── homebridge-temperature-file@1.0.0
├─┬ homebridge-yamaha@0.0.1 (git://github.com/neonightmare/homebridge-yamaha#b19306ba1fd7f7df3fd1f52114f9d8a49feed6bc)
```

...and configured it:

```
        [...]
        {
                "platform": "YamahaAVR",
                "play_volume": -48,
                "setMainInputTo": "Airplay",
                "manual_addresses": {
                        "Yamaha": "192.168.0.19"
                }
        } 
        [...]
```

...but it doesn't appear to be detected ("registered"?) in Homebridge?

```
Error: The requested platform 'YamahaAVR' was not registered by any plugin.
```

Full output:

```
$ homebridge

Loaded plugin: homebridge-http
Registering accessory 'homebridge-http.Http'

---
Loaded plugin: homebridge-ifttt
Registering platform 'homebridge-ifttt.IFTTT'

---
Loaded plugin: homebridge-temperature-file
Registering accessory 'homebridge-temperature-file.TemperatureFile'

---
Loaded plugin: homebridge-yamaha
Registering accessory 'homebridge-yamaha.Yamaha'
Registering platform 'homebridge-yamaha.Yamaha'

---
Loaded config.json with 1 accessories and 2 platforms.

---
Loading 2 platforms...
[IFTTT] Initializing IFTTT platform...
[IFTTT] Loading accessories...
[IFTTT] Found: Accessory 1
[IFTTT] Loading service: A1-1, subtype: T1-1OnT1-1Off
[IFTTT] Loading service: A1-2, subtype: T1-2OnT1-2Off
[IFTTT] Loading service: A1-3, subtype: T1-3
[IFTTT] Loading service: A1-4, subtype: T1-4
[IFTTT] Found: Accessory 2
[IFTTT] Loading service: A2-1, subtype: T2-1
[IFTTT] Loading service: A2-2, subtype: T2-2
[IFTTT] Loading service: A2-3, subtype: T2-3
[IFTTT] Loading service: A2-4, subtype: T2-4
[IFTTT] Initializing platform accessory 'Accessory 1'...
[IFTTT] Initializing platform accessory 'Accessory 2'...

/Users/vs/.nvm/v0.10.38/lib/node_modules/homebridge/lib/api.js:88
      throw new Error("The requested platform '" + name + "' was not registere
            ^
Error: The requested platform 'YamahaAVR' was not registered by any plugin.
    at API.platform (/Users/vs/.nvm/v0.10.38/lib/node_modules/homebridge/lib/api.js:88:13)
    at Server._loadPlatforms (/Users/vs/.nvm/v0.10.38/lib/node_modules/homebridge/lib/server.js:185:45)
    at Server.run (/Users/vs/.nvm/v0.10.38/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/Users/vs/.nvm/v0.10.38/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/Users/vs/.nvm/v0.10.38/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

Any idea?

**Comment by MPV** [comment]
Or is this plugin not ready yet?

Should I/we be using the "legacy" plugin for Yamaha AVR instead?
- https://github.com/nfarina/homebridge-legacy-plugins
- https://github.com/nfarina/homebridge-legacy-plugins/blob/master/platforms/YamahaAVR.js

**Comment by neonightmare** [comment]
should now work, bugfix
