### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by RangerRick** [neonightmare/homebridge-yamaha#9]
- node 6.2.1
- homebridge 0.3.4
- homebridge-yamaha 0.0.5-alpha.1
- ubuntu 16.04

config:

```
  "platforms": [{
    "platform": "YamahaAVR",
    "play_volume": -48,
    "setMainInputTo": "Airplay",
    "manual_addresses": {
      "Yamaha": "192.168.211.12"
    }
  }],
```

When homebridge-yamaha attempts to find devices over mDNS, homebridge crashes with the following error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/opt/node-v6.2.1-linux-x64/lib/node_modules/homebridge-yamaha/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/opt/node-v6.2.1-linux-x64/lib/node_modules/homebridge-yamaha/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/opt/node-v6.2.1-linux-x64/lib/node_modules/homebridge-yamaha/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by RangerRick** [comment]
As you can see, I attempted to manually define my receiver in case that helps, but it appears it does the mDNS scan anyways.

It _does_ see my manually configured receiver properly and detects the model, so that part seems to be OK...

**Comment by seppelicous** [comment]
I am facing the same error with Homebridge and Docker on my NAS. Node V8.9.1
It would be awesome if a developer could support.

**Comment by NorthernMan54** [comment]
And googling it shows this

Just for your information, getaddrinfo error codes can be translated into human-readable text using gai_strerror, defined in netdb.h <http://pubs.opengroup.org/onlinepubs/7908799/xns/netdb.h.html>. Unfortunately, the error code -3008 is represented as "Unknown error". My guess is that the error code comes from somewhere else than the getaddrinfo function, perhaps some underlying system call or whatever... 

I’m thinking a Docker config issue

**Comment by leotsem** [comment]
Getting the same error when running [Homebridge via Docker on my Synology NAS](https://github.com/oznu/homebridge-syno-spk). I'm getting this warning on the Homebridge console, if that helps:
```*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>```
